# Generated by Django 4.1 on 2022-09-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=128)),
                ('apellido', models.CharField(default='', max_length=128)),
                ('codigo', models.CharField(default='', max_length=128)),
                ('direccion', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
