# Generated by Django 4.1 on 2022-09-03 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichangasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipo_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=128)),
                ('arquero', models.CharField(default='', max_length=32)),
                ('defensa_1', models.CharField(default='', max_length=32)),
                ('defensa_2', models.CharField(default='', max_length=32)),
                ('volante_1', models.CharField(default='', max_length=32)),
                ('volante_2', models.CharField(default='', max_length=32)),
                ('volante_3', models.CharField(default='', max_length=32)),
                ('delantero_1', models.CharField(default='', max_length=32)),
                ('delantero_2', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='pichanga_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('marcador_local', models.CharField(default='0', max_length=128)),
                ('marcador_visita', models.CharField(default='0', max_length=128)),
                ('equipo_local', models.CharField(default='0', max_length=128)),
                ('equipo_visita', models.CharField(default='0', max_length=128)),
                ('estadoPichanga', models.CharField(default='Programada', max_length=128)),
            ],
        ),
    ]
