# Generated by Django 4.1 on 2022-09-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=128)),
                ('apellido', models.CharField(default='', max_length=128)),
                ('edad', models.CharField(default='', max_length=32)),
                ('direccion', models.CharField(default='', max_length=256)),
                ('categoria', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
